# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Not Bayesian Enough
tagline:           
url:              http://www.notbayesianenough.com
paginate:         1
baseurl:          /
shorturl:         notbayesianenough.com
author:
  name:           Tenoke
  url:            https://notbayesianenough.com
  email:          admin@notbayesianenough.com
  


# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/Tenoke/Tenoke.github.io
  
#pages to include in the header
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
